insert into suppliers (id, country_code, name) values (1, 1, 'Nolan, Senger and Ruecker');
insert into suppliers (id, country_code, name) values (2, 9, 'Schmitt, Wiegand and Zieme');
insert into suppliers (id, country_code, name) values (3, 5, 'Mayer-Gaylord');
insert into suppliers (id, country_code, name) values (4, 6, 'Volkman LLC');
insert into suppliers (id, country_code, name) values (5, 10, 'Blanda Group');
insert into suppliers (id, country_code, name) values (6, 5, 'Medhurst-Becker');
insert into suppliers (id, country_code, name) values (7, 20, 'Torphy, Morissette and Murray');
insert into suppliers (id, country_code, name) values (8, 17, 'Bode-Brekke');
insert into suppliers (id, country_code, name) values (9, 13, 'Brown, Goodwin and Rath');
insert into suppliers (id, country_code, name) values (10, 7, 'Reichert-Ledner');
insert into suppliers (id, country_code, name) values (11, 13, 'Reichert-Orn');
insert into suppliers (id, country_code, name) values (12, 18, 'Dicki, O''Reilly and Harris');
insert into suppliers (id, country_code, name) values (13, 2, 'Hamill Group');
insert into suppliers (id, country_code, name) values (14, 3, 'Rohan Group');
insert into suppliers (id, country_code, name) values (15, 20, 'Anderson, Lind and Harris');
insert into suppliers (id, country_code, name) values (16, 4, 'Abshire-Skiles');
insert into suppliers (id, country_code, name) values (17, 14, 'O''Keefe-Bashirian');
insert into suppliers (id, country_code, name) values (18, 10, 'Littel-Cronin');
insert into suppliers (id, country_code, name) values (19, 9, 'Skiles LLC');
insert into suppliers (id, country_code, name) values (20, 16, 'Romaguera, Kuphal and Lockman');
insert into suppliers (id, country_code, name) values (21, 15, 'Larson-Gleichner');
insert into suppliers (id, country_code, name) values (22, 12, 'Graham-Homenick');
insert into suppliers (id, country_code, name) values (23, 8, 'Thompson-Kshlerin');
insert into suppliers (id, country_code, name) values (24, 3, 'Nitzsche, Conroy and Cruickshank');
insert into suppliers (id, country_code, name) values (25, 4, 'Feil LLC');
insert into suppliers (id, country_code, name) values (26, 13, 'D''Amore-Ratke');
insert into suppliers (id, country_code, name) values (27, 6, 'Hoppe Group');
insert into suppliers (id, country_code, name) values (28, 7, 'Dickens LLC');
insert into suppliers (id, country_code, name) values (29, 5, 'Hickle Group');
insert into suppliers (id, country_code, name) values (30, 11, 'Senger-Crist');
insert into suppliers (id, country_code, name) values (31, 6, 'Hermiston LLC');
insert into suppliers (id, country_code, name) values (32, 11, 'Boyle-Kemmer');
insert into suppliers (id, country_code, name) values (33, 14, 'Leffler, Boyle and Connelly');
insert into suppliers (id, country_code, name) values (34, 10, 'Grant Inc');
insert into suppliers (id, country_code, name) values (35, 14, 'Gerlach and Sons');
insert into suppliers (id, country_code, name) values (36, 12, 'Stiedemann-Wintheiser');
insert into suppliers (id, country_code, name) values (37, 12, 'Walker-Rolfson');
insert into suppliers (id, country_code, name) values (38, 2, 'Bradtke-Shields');
insert into suppliers (id, country_code, name) values (39, 16, 'Hahn-Dickens');
insert into suppliers (id, country_code, name) values (40, 11, 'Adams Group');
insert into suppliers (id, country_code, name) values (41, 18, 'Cronin-Terry');
insert into suppliers (id, country_code, name) values (42, 4, 'Bradtke-Champlin');
insert into suppliers (id, country_code, name) values (43, 14, 'Rutherford-Corwin');
insert into suppliers (id, country_code, name) values (44, 8, 'Cassin and Sons');
insert into suppliers (id, country_code, name) values (45, 2, 'Konopelski LLC');
insert into suppliers (id, country_code, name) values (46, 16, 'Murray, Erdman and Marks');
insert into suppliers (id, country_code, name) values (47, 12, 'Hand, Wiegand and Lind');
insert into suppliers (id, country_code, name) values (48, 2, 'Auer LLC');
insert into suppliers (id, country_code, name) values (49, 16, 'Hansen, Collier and Botsford');
insert into suppliers (id, country_code, name) values (50, 15, 'Hayes Group');
